export const WORLD_CUP_2026_TEAM_CONDUCT_SCORES = new Map<string, number>([
  ["Noruega", -1],
  ["Francia", -1],
  ["Japón", -1],
  ["Alemania", -1],
  ["Jordania", -1],
  ["Argelia", -1],
  ["República Checa", -1],
  ["Marruecos", -1],
  ["Túnez", -1],
  ["Croacia", -2],
  ["Inglaterra", -2],
  ["España", -2],
  ["Senegal", -2],
  ["Argentina", -2],
  ["Suiza", -3],
  ["Ghana", -3],
  ["Austria", -3],
  ["Turquía", -3],
  ["Países Bajos", -3],
  ["Uzbekistán", -4],
  ["Cabo Verde", -4],
  ["Colombia", -4],
  ["Costa de Marfil", -4],
  ["República de Corea", -4],
  ["Portugal", -4],
  ["Nueva Zelanda", -4],
  ["RD de Congo", -5],
  ["Estados Unidos", -5],
  ["Panamá", -5],
  ["Australia", -5],
  ["Suecia", -5],
  ["Ecuador", -5],
  ["Escocia", -5],
  ["Brasil", -5],
  ["Canadá", -5],
  ["Egipto", -6],
  ["Irán", -6],
  ["México", -6],
  ["Arabia Saudí", -6],
  ["Curazao", -7],
  ["Haití", -7],
  ["Bélgica", -7],
  ["Irak", -8],
  ["Uruguay", -9],
  ["Bosnia y Herzegovina", -10],
  ["Paraguay", -12],
  ["Catar", -12],
  ["Sudáfrica", -13],
]);

export const WORLD_CUP_2026_FIFA_RANKINGS = new Map<string, number>();
